export const works = [
  {
    src: '/assets/works/twenty-twenty/',
    label: 'Twenty&Twenty',
    url: 'twenty-twenty',
    images: 6,
    description: 'Twenty&Twenty is a bold, creative film production company that transforms stories into visually striking films. With an emphasis on authentic storytelling, the team collaborates closely with clients to shape each project uniquely, from concept development through to post-production. Whether crafting an impactful brand film, producing a gripping short, or building a series that resonates, they dive deep into every project, seamlessly blending technical skill with artistic vision.',
  },
  {
    src: '/assets/works/solvita/',
    label: 'Solvita',
    url: 'solvita',
    images: 8,
    description: 'Solvita is a personalized mobile messaging platform that helps brands and businesses stay in touch with their customers. Solvita provides a suite of tools to create and manage mobile campaigns, including message templates, scheduling, and reporting. Solvita\'s platform is fully customizable and easy to use, making it the perfect solution for any business that wants to improve its customer communication.',
  },
  {
    src: '/assets/works/picarius/',
    label: 'Picarius',
    url: 'picarius',
    images: 1,
    description: 'Picarius is an on-demand mobile marketplace that helps travelers discover & book the most incredible tours, activities, events & local experiences in town for the next 24 hours at exclusive discounted prices.',
  },
  {
    src: '/assets/works/scherer-architekten/',
    label: 'Scherer Architekten',
    url: 'scherer-architekten',
    images: 7,
    description: 'Scherer Architekten is a forward-thinking architectural firm located in Liestal, Switzerland, known for its distinctive approach to design that marries innovation with local context. The firm specializes in crafting unique spaces that not only meet the practical needs of their clients but also resonate with the surrounding environment.'
  },
  {
    src: '/assets/works/delenty/',
    label: 'Delenty',
    url: 'delenty',
    images: 5,
    description: 'Delenty is an online platform that provides a way for everyone to buy and sell second-hand furniture and decor. Customers can find their perfect match and get it delivered to their door without moving from their sofa.',
  },
  {
    src: '/assets/works/hummal/',
    label: 'Hummal',
    url: 'hummal',
    images: 5,
    grid: [4, 5],
    description: 'Hummal is the global leader in the development and application of artificial intelligence solutions for the IT industry. They partner with the world\'s leading organizations to transform operational outcomes with personalized AI-driven technology. Their interdisciplinary teams consist of experienced engineers and data scientists dedicated to advancing innovation and enhancing user experiences.',
  },
  {
    src: '/assets/works/ricardo-skinner-gallery/',
    label: 'Ricardo Skinner Gallery',
    url: 'ricardo-skinner-gallery',
    images: 6,
    grid: [2, 3, 4, 5],
    description: 'Set up in 2010, Ricardo Skinner Gallery is a Torino-based contemporary art gallery. The gallery began with a primary focus on contemporary photography and image-based art and has evolved to include diverse media in contemporary art. The gallery represents mainly emerging and established Italian and European artists.',
  },
  {
    src: '/assets/works/designdots/',
    label: 'designdots',
    url: 'designdots',
    images: 6,
    description: 'Designdots is a creative conference that brings together designers, photographers, artists and programmers with the aim of exchanging knowledge and experiences through various workshops, lectures and projects.',
  },
  {
    src: '/assets/works/idukki/',
    label: 'Idukki',
    url: 'idukki',
    images: 4,
    description: 'Idukki is a premier Japanese food restaurant located in Riyadh, Saudi Arabia, offering an authentic dining experience that captures the essence of Japanese cuisine. With a menu that features a wide array of traditional dishes, from sushi and sashimi to ramen and tempura, Idukki delights diners with its commitment to quality and flavor. The restaurant\'s inviting atmosphere is enhanced by its elegant design and attentive service, making it the perfect destination for both casual meals and special occasions. Idukki not only serves delicious food but also fosters a cultural connection, bringing the rich culinary traditions of Japan to the heart of Riyadh.',
  },
  {
    src: '/assets/works/jennet/',
    label: 'Jennet',
    url: 'jennet',
    images: 7,
    grid: [6, 7],
    description: 'Jennet is a payment service provider that allows one to make purchases using crypto. Jennet is not limited to purchases; you can also buy, swap or store your crypto coins on the app.',
  },
  {
    src: '/assets/works/daisen/',
    label: 'Daisen',
    url: 'daisen',
    images: 7,
    grid: [6, 7],
    description: 'Daisen is an online platform for editing social media videos, offering intuitive tools, templates, and effects. It empowers creators to produce engaging content that captures attention and enhances audience connection.',
  },
  {
    src: '/assets/works/avacus/',
    label: 'Avacus',
    url: 'avacus',
    images: 2,
    description: 'Avacus is a startup that was founded in 2021 and is currently based in Tokyo, Japan. The company is behind the development and manufacturing of increasingly advanced prototypes for flying cars. They have a vision to unclog the roadways on the ground and improve the way we travel.',
  },
  {
    src: '/assets/works/monto/',
    label: 'Monto',
    url: 'monto',
    images: 5,
    grid: [3, 4],
    description: 'Monto is an online platform offering financial tools tailored for small and medium-sized businesses in the crypto industry. It provides users with essential resources for managing transactions, tracking investments, and optimizing financial strategies. With user-friendly features and robust analytics, Monto empowers businesses to navigate the evolving crypto landscape effectively, ensuring they stay competitive and informed. The platform’s commitment to security and transparency further enhances trust, making it an invaluable partner for businesses looking to thrive in the dynamic world of cryptocurrency.',
  },
  {
    src: '/assets/works/daeidilan/',
    label: 'Daeidilan',
    url: 'daeidilan',
    images: 3,
    description: 'Daedalean offers real-time cargo tracking and monitoring, as well as cloud-based data analytics, to give supply chain visibility.',
  },
  {
    src: '/assets/works/salvatierra/',
    label: 'Salvatierra',
    url: 'salvatierra',
    images: 3,
    description: 'Reminiscent of her grandmothe\'s habits of wearing beautiful saris every day, Ivette envisions a line of well-designed items that are meant to be worn and used often. Each item is hand-picked and locally produced, forming a series of long-lasting, sustainable, and beautiful items that are meant to stay with you and be passed down to later generations. Salvatierra is a lifestyle fashion brand designed by Ivette Salvatierra.',
  },
  {
    src: '/assets/works/sfas/',
    label: 'Society for artistic support',
    url: 'sfas',
    images: 4,
    description: 'Society for Artistic Support (SAS) is an organization that advocates for the rights of creative professionals in the United States. They focus on issues such as copyright protection, intellectual property rights, and fair compensation for artists, writers, musicians, and other creatives. The SAS works to raise awareness and educate the public about the importance of creative rights, while also lobbying for legislative and policy changes that support and protect those rights. The organization serves as a unified voice for the creative community, promoting collaboration and engagement among its members',
  },
];
